# Generated by Django 4.0.2 on 2022-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Имя')),
                ('balance_toncoin', models.FloatField(verbose_name='Баланс Toncoin')),
                ('freeze_balance_toncoin', models.FloatField(verbose_name='Замороженный баланс Toncoin')),
                ('date_registration', models.DateTimeField(verbose_name='Дата регистрации')),
                ('count_deals', models.IntegerField(verbose_name='Количество сделок')),
            ],
            options={
                'verbose_name': '👤 Пользователь',
                'verbose_name_plural': '👥 Пользователи',
                'db_table': 'users',
            },
        ),
    ]
