# Generated by Django 3.2.13 on 2022-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0001_initial'),
    ]

    operations = [

    ]
