# Generated by Django 4.0.2 on 2022-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('cryptocurrency', models.TextField(verbose_name='Криптовалюта')),
                ('is_sell', models.BooleanField(verbose_name='Продажа?')),
                ('currency', models.TextField(verbose_name='Валюта')),
                ('category_id', models.IntegerField(verbose_name='ID категории')),
                ('subCategory_id', models.IntegerField(verbose_name='ID подкатегории')),
                ('fixPrice', models.FloatField(blank=True, null=True, verbose_name='Фиксированная цена')),
                ('percent', models.FloatField(blank=True, null=True, verbose_name='Проценты')),
                ('decimalPercent', models.TextField(blank=True, null=True, verbose_name='Знак процентов')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('dateCreated', models.DateTimeField(verbose_name='Дата создания')),
                ('limitLow', models.FloatField(verbose_name='Нижний лимит')),
                ('limitHigh', models.FloatField(verbose_name='Верхний лимит')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Список объявлений',
                'db_table': 'adverts',
            },
        ),
    ]
