# Generated by Django 4.0.2 on 2022-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='ID Категории')),
                ('subcategory_id', models.IntegerField(verbose_name='ID Подкатегории')),
                ('advert_id', models.IntegerField(verbose_name='ID Объявления')),
                ('creator_user_id', models.BigIntegerField(verbose_name='User ID создателя объявления')),
                ('creator_mess_id', models.IntegerField(blank=True, null=True, verbose_name='Mess ID создателя объявления')),
                ('user_id', models.BigIntegerField(verbose_name='User ID создателя сделки')),
                ('user_mess_id', models.IntegerField(blank=True, null=True, verbose_name='Mess ID создателя сделки')),
                ('is_sell', models.BooleanField(verbose_name='Сделка по продаже?')),
                ('cryptocurrency', models.TextField(verbose_name='Криптовалюта')),
                ('currency', models.TextField(verbose_name='Валюта')),
                ('amount_crypto', models.FloatField(verbose_name='Сумма сделки в крипте')),
                ('amount_currency', models.FloatField(verbose_name='Сумма сделки в валюте')),
                ('status_start', models.BooleanField(verbose_name='Сделка началась?')),
                ('payment', models.TextField(blank=True, null=True, verbose_name='Реквизиты')),
                ('status_finish', models.BooleanField(verbose_name='Сделка завершена?')),
                ('status_arbitr', models.BooleanField(verbose_name='Сделка в арбитраже?')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала сделки')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сделки')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deal',
            },
        ),
    ]
