# Generated by Django 3.2.13 on 2022-07-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_deposit_for_sell',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Был депозит со стороны продавца?'),
        ),
    ]
