# Generated by Django 4.0.2 on 2022-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='ID категории')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Список подкатегорий',
                'db_table': 'subcategories',
            },
        ),
    ]
