# Generated by Django 4.0.2 on 2022-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('course', models.FloatField(verbose_name='Курс 1 монета к доллару')),
                ('course_rub', models.FloatField(verbose_name='Курс 1 монета к рублю')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы криптовалют/фиат',
                'db_table': 'courses',
            },
        ),
    ]
